name: Code Coverage
on:
  push:
    branches:
      - develop
jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Create Environment Files
        run: node server.js && node server-cypress.js
        env:
          ENVIRONMENT_FILE: '${{ secrets.ENVIRONMENT_FILE }}'
          ACCOUNTS_FILE: '${{ secrets.ACCOUNTS_FILE }}'
      - name: Install Dependencies
        run: npm ci
      - name: Run All Tests With Coverage
        run: npm run tests:all
      - name: Update Code Coverage Badge
        run: npx update-badge --from coverage/merged-report/coverage-summary.json
      - name: Set Code Coverage Commit Status
        run: npx -p check-code-coverage set-gh-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ensure Coverage Has Not Dropped
        run: npx -p check-code-coverage set-gh-status --check-against-readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply code coverage badge update
          branch: ${{ github.head_ref }}
