name: ci
on: [ push ]
jobs:
  env-setup:
    runs-on: ubuntu-22.04
    outputs:
      ENVIRONMENT_FILE: ${{ secrets.ENVIRONMENT_FILE }}
      ACCOUNTS_FILE: ${{ secrets.ACCOUNTS_FILE }}
    steps:
      - run: echo "Setup Environment Variables"
  test:
    # https://github.com/bahmutov/cypress-workflows
    needs: env-setup
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
    with:
      nE2E: 5
      nComponent: 23
      start: npm start
      wait-on: npx wait-on --timeout 600000 http://localhost:4200
      coverage: true
      before-run: node server.js && node server-cypress.js
      ENVIRONMENT_FILE: ${{ needs.vars.outputs.ENVIRONMENT_FILE }}
      ACCOUNTS_FILE: ${{ needs.vars.outputs.ACCOUNTS_FILE }}
