name: Deploy to Firebase Hosting on PR
on: pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Create Environment File
        run: node server.js
        env:
          ENVIRONMENT_FILE: '${{ secrets.ENVIRONMENT_FILE }}'
      - name: Install Dependencies & Build
        run: npm ci && npm run build
      - name: Firebase Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_USERSROLE }}'
          projectId: usersrole
